### ISSUE TITLE
Bug avec dossier plugin

### ISSUE THREAD

**Issue by djgsi974** [QuentinCG/jarvis-radio-tv#1]
Bonjour. Il y a un message d'erreur à cause du  dossier "plugin" qui a été séparé en deux dossiers : "plugins_enabled" et "plugins_installed". J'ai modifié en local sur mon raspberry et réussi à faire fonctionner et à ajouter d'autres radios, donc cool, ça fonctionne (pas testé tv ceci dit). Par contre, je ne sais pas comment renvoyer tout ça et je ne veux surtout pas foutre la m... :-)
Si y'aurait moyen de m'expliquer, ou de corriger le pb. Au cas où ci-joint le dossier du plugin modifié.
[jarvis-radio-tv.zip](https://github.com/QuentinCG/jarvis-radio-tv/files/1405741/jarvis-radio-tv.zip)

En tous cas, merci pour le travail effectué.

A bientôt !

**Comment by QuentinCG** [comment]
Bonjour,

Merci pour ton feedback et ton aide.

Je viens de rajouter tes changements dans le code: https://github.com/QuentinCG/jarvis-radio-tv/commit/f4874684fdcfa1438295f987bc874a34559eda68

Tu as été rajouté dans la liste des contributeurs: https://github.com/QuentinCG/jarvis-radio-tv

Si à l'avenir tu veux faire une demande pour modifier un projet sur github (faire un "pull request"), je te conseille de suivre cette procédure: http://www.louisfelix.org/node/36 (si ce n'est toujours pas clair, voici un tuto un peu plus détaillé: https://blog.zenika.com/2017/01/24/pull-request-demystifie/)

Pour ce qui est de ton soucis avec "plugins_enabled" et "plugins_installed", il est etrange que tu ais eu un soucis sachant que ca devrait etre géré directement par Jarvis lors de l'installation. Notes que les deux dossiers en question pointent en réalité vers le même dossier (modifier l'un modifiera l'autre).

**Comment by QuentinCG** [comment]
Again, thank you
